name = "LucceGuido"
author = "Lucce Guido"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6b9a9f75069bca8b4c0994ad46058c3675d7a20e558fd820c2b020b182160593"

[versions]
forge = "47.4.18"
minecraft = "1.20.1"
