name = "LucceGuido"
author = "Lucce Guido"
version = "1.0.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3c74a78c464e3c91885308f039d356c9986e818a2b609ab0d5ef292c07c53549"

[versions]
forge = "47.4.18"
minecraft = "1.20.1"
