name = "LucceGuido"
author = "Lucce Guido"
version = "1.0.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fb5f4b7f6a913ced176dec8dbe6881fc9260990a1f7bcb04c70d8ef47f2c9407"

[versions]
forge = "47.4.18"
minecraft = "1.20.1"
