name = "WOC_remastered_patch"
filename = "WOC-Remastered-1.3.0-forge-1.20.1-broad-patched-v6.jar"
side = "both"

[download]
url = "https://github.com/Fishcakes39/LucceGuido/raw/refs/heads/main/custom_jars/WOC-Remastered-1.3.0-forge-1.20.1-broad-patched-v6.jar"
hash-format = "sha256"
hash = "073c8cb2d203afdde2c0919e5b6dd50290c67a1f3455d4ecf9a8cfc95daecb9a"
